name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Pacman Chart
        run: |
          curl -s "https://ghchart.rshah.org/thaissthephanye" > pacman-contribution-graph.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pacman-contribution-graph.svg
          git commit -m "Update Pacman chart" || exit 0
          git push
