name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Pacman
        uses: marwin1991/pacman-contribution-graph@main
        with:
          github_user_name: thaissthephanye
          output_svg: pacman-contribution-graph.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pacman-contribution-graph.svg
          git commit -m "Update Pacman animation - $(date)" || exit 0
          git push
